### ISSUE TITLE
How to bump `MICRO`?

### ISSUE THREAD

**Issue by KubaJastrz** [casmith/release-it-calver-plugin#1]
format: `YY.MM.MICRO`
current date: 2020-09-14

going from `20.8.4` to `20.9.0` works, but then the version won't be bumped again till next month

**Comment by Duncank** [comment]
You can revert this fix by upgrading calver to the latest version; since it is fixed in there now!

It now works like this by default:
```js
var version = new calver('YYYY.MM.MICRO', '2020.11.5');
version.inc(); // 2020.12.0

var version = new calver('YYYY.MM.MICRO', '2020.12.5');
version.inc(); // 2020.12.6
```

**Comment by casmith** [comment]
> You can revert this fix by upgrading calver to the latest version; since it is fixed in there now!
> 
> It now works like this by default:
> 
> ```js
> var version = new calver('YYYY.MM.MICRO', '2020.11.5');
> version.inc(); // 2020.12.0
> 
> var version = new calver('YYYY.MM.MICRO', '2020.12.5');
> version.inc(); // 2020.12.6
> ```

Thanks for pointing this out! I've upgraded calver to the latest version and it looks good now.
