### ISSUE TITLE
Is it possible to merge semver and calver to achieve version format like YY.MM.MINOR.PATCH?

### ISSUE THREAD

**Issue by EugeneBran** [casmith/release-it-calver-plugin#10]
Hello. is it possible to merge semver and calver to achieve version format like YY.MM.MINOR.PATCH?
I'am trying to do this with release-it-calver-plugin but i get errors like
`ERROR Version and format lengths mismatch.`
And when i'm setting "format": "YY.MM.MICRO", there is error message `ERROR Invalid month.`

**Comment by casmith** [comment]
Try with `format: "yy.mm.minor.patch"`. It should work in the latest version.

**Comment by casmith** [comment]
Closing this issue as it should be resolved in latest version. @EugeneBran please revert back if you have any issues.
