### ISSUE TITLE
Is there an option to only increment date part (year and month)?

### ISSUE THREAD

**Issue by andorfermichael** [casmith/release-it-calver-plugin#13]
I was wondering if I can configure release-it via command line in a way that release-it-calver-plugin only increases the date parts of the version.

For example, I have a master branch and a release branch.

Both year and month should be updated on master branch - every day (scheduled pipeline executing release-it) and or every time a pipeline runs (e.g. merge request pipeline executing release-it). The minor/patch versions however should be increased only when master is merged into release branch and thus a release with tag is created.

The main reason is that there are months in which no release is done and thus if this option is not available, the year and month would be wrong for our test and staging environments when year and/or month changed. However, if I run release-it on those environments the minor/patch counter would be wrong.

So my question is if there is a configuration option to do so?

**Comment by uturnr** [comment]
You could try:
```json
{
  "format": "<your format>",
  "increment": "calendar",
  "fallbackIncrement": "calendar"
}
```
