### ISSUE TITLE
ERROR Plugin.isEnabled is not a function

### ISSUE THREAD

**Issue by SimoneCusimano** [casmith/release-it-calver-plugin#5]
Hello,
I'm having trouble with the newly released version of the plugin: 1.0.3.
The _release-it_ version is 14.6.2

I run the following command:
```npx release-it --ci --disable-metrics --no-git.tag --no-git.push```

The output is as follows:
```ERROR Plugin.isEnabled is not a function```

Here is the configuration of the _.release-it.json_ file
```
{
   "hooks": {
     "after: release": "echo ${version} > VERSION && echo ${latestVersion} > LATEST_VERSION"
   },
   "git": {
     "commit": false,
     "requireUpstream": false,
     "requireCleanWorkingDir": false,
     "tagName": "v${version}"
   },
   "npm": {
     "publish": false,
     "ignoreVersion": true,
     "skipChecks": true
   },
   "plugins": {
     "@csmith/release-it-calver-plugin": {
       "format": "YY.0M.MICRO"
     }
   },
   "verbose": 2
}
```

**Comment by casmith** [comment]
Hey, thanks for reporting. I just released 1.0.4 which should resolve it. Please give it a try and let me know.

**Comment by casmith** [comment]
Or better yet, 2021.5.1

**Comment by SimoneCusimano** [comment]
Hi @casmith, it looks ok now. Thanks!
