### ISSUE TITLE
Version is not updated properly

### ISSUE THREAD

**Issue by SimoneCusimano** [casmith/release-it-calver-plugin#6]
Hello,
apparently, **the version is not updated correctly**.

The latest git tag present is: **v21.03.0**

Running the plugin today (we are in May), I expect the version to be **v21.05.0**

Instead, I get: **v21.03.1**

**It seems that only the micro is bumped. The calendar part is ignored.**

I would suggest refining the _getIncrementedVersion_ function [here](https://github.com/casmith/release-it-calver-plugin/blob/master/calver-plugin.js#L13-L16).

I am using the latest versions:
```
release-it@14.7.0
@csmith/release-it-calver-plugin@2021.5.4
```

Here is the configuration of the _.release-it.json_ file:
```
{
   "hooks": {
     "after: release": "echo ${version} > VERSION && echo ${latestVersion} > LATEST_VERSION"
   },
   "git": {
     "commit": false,
     "requireUpstream": false,
     "requireCleanWorkingDir": false,
     "tagName": "v${version}"
   },
   "npm": {
     "publish": false,
     "ignoreVersion": true,
     "skipChecks": true
   },
   "plugins": {
     "@csmith/release-it-calver-plugin": {
       "format": "YY.0M.MICRO"
     }
   },
   "verbose": 2
}
```

Please note that using the following versions, the plugin works properly:
```
release-it@14.7.0
@csmith/release-it-calver-plugin@1.0.2
calver@20.5.3
```

**Comment by casmith** [comment]
Hey, thanks again for reporting. Please try [2021.5.7](https://github.com/casmith/release-it-calver-plugin/releases/tag/v2021.5.7). 

I'm basically trying to bump the calendar version first, and if it doesn't result in a new version. then micro is incremented.
