### ISSUE TITLE
PreRelease Support

### ISSUE THREAD

**Issue by jtbairdsr** [casmith/release-it-calver-plugin#7]
I can't seem to get pre-release tags to show up... I am using the following format `YY.MM.MICRO.MODIFIER` but all I ever get is `YY.MM.MICRO`

**Comment by fathert0rque** [comment]
@jtbairdsr I needed this as well, [according to the node-calver docs](https://github.com/muratgozel/node-calver#choose-format) the modifier would have to be passed in to the plugin here https://github.com/casmith/release-it-calver-plugin/blob/master/calver-plugin.js#L16, but it's being hard-coded to `calendar`. It would be easy to fork

**Comment by casmith** [comment]
> @jtbairdsr I needed this as well, [according to the node-calver docs](https://github.com/muratgozel/node-calver#choose-format) the modifier would have to be passed in to the plugin here https://github.com/casmith/release-it-calver-plugin/blob/master/calver-plugin.js#L16, but it's being hard-coded to `calendar`. It would be easy to fork

Or someone could raise a pull request?

**Comment by casmith** [comment]
@jtbairdsr I added support for tags like alpha, dev etc (those supported by calver). Does this give you what you need? 

You can now set the increment option in the plugin configuration. See Readme for an example.
