### ISSUE TITLE
calver 21.11 breaks plugin.

### ISSUE THREAD

**Issue by aloysius-lim** [casmith/release-it-calver-plugin#8]
Running release-it-calver-plugin with the latest versions of calver leads to the following error:

```
ERROR calver.init is not a function
```

This is due to a codebase refactor introduced in [calver v21.11.0](https://github.com/muratgozel/node-calver/releases/tag/v21.11.0), which removes `calver.init()`.

Workaround: Install older version of calver, e.g. `"calver": "~21.1.3"`.

**Comment by casmith** [comment]
Upgraded to latest version of calver. Let me know if any issues
